[project]
name = "largelanguagemodel"
version = "0.1.0"
description = "Experimenting with LLMs"
requires-python = ">=3.13"

[dependency-groups]
dev = [
    "pyright>=1.1.401",
    "pytest>=8.3.5",
    "ruff>=0.11.11",
]
